### ISSUE TITLE
Safari/iOS build bug

### ISSUE THREAD

**Issue by MikeBild** [xing/hops#217]
Current situation:

Safari/iOS error after `npm run build`

![safari-error](https://user-images.githubusercontent.com/179382/30335386-84ea3a48-97e2-11e7-9bf0-a0ba5d0f2989.png)

Current findings:

* Different `index.html` outputs after using a "custom" buildConfig with the same build options in plugins (using the babel-minify-webpack-plugin) section:

```javascript
new BabelMinifyPlugin(
  { evaluate: false, mangle: false, propertyLiterals: false },
  { comments: false }
)
```

`npm run build` output:

[hops624-index-html.txt](https://github.com/xing/hops/files/1296551/hops624-index-html.txt)
[custombuildrc-index-html.txt](https://github.com/xing/hops/files/1296550/custombuildrc-index-html.txt)

custom build config:

```javascript
const baseBuildConfig = Object.assign({}, require('hops-config/configs/build'));
const BabelMinifyPlugin = require('babel-minify-webpack-plugin');

baseBuildConfig.plugins = baseBuildConfig.plugins
  .filter(x => x.constructor.name !== 'BabelMinifyPlugin')
  .concat([
    new BabelMinifyPlugin(
      { evaluate: false, mangle: false, propertyLiterals: false },
      { comments: false }
    )
  ])

module.exports = baseBuildConfig;
```

**Comment by dmbch** [comment]
@MikeBild thanks for reporting this and for your earlier PR! This issue is unfortunately rather hard to reproduce... I went ahead and diffed the two HTML files you provided. I didn't actually see any differences except those caused by disabling mangling:

`git diff --word-diff=color --word-diff-regex=. hops624-index-html.txt custombuildrc-index-html.txt'`

In your original pull request, you only deactivated the [property literal transform](https://github.com/babel/minify/tree/master/packages/babel-plugin-transform-property-literals), but left the [mangle names plugin](https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-mangle-names) active. So, could it be that that's the actual culprit? If so, we could try tweaking the [mangling plugin config](https://github.com/babel/minify/tree/master/packages/babel-preset-minify#options) instead of disabling it altogether. 

Anyway, I'd love to find out where that stray [蕄 (Han, `\u8544`)](http://www.fileformat.info/info/unicode/char/8544/index.htm) character is coming from. Understanding that might help us tweak the minifier plugin config. It does not appear to be in the HTML files. So, can you help me out in this regard?

**Comment by MikeBild** [comment]
Hi,

"In your original pull request, you only deactivated the property literal transform, but left the mangle names plugin active."

I deactivate **mangle** and **propertyLiterals** on both sides. (to be exact by patching `node_modules/hops-config/configs/build.js`). That's one of the issue. It seems to be, that the modified minifier options in `build.js` are not correctly applied to the "standard/base " hops build process.

**Comment by dmbch** [comment]
This smells like an issue with multiple versions of hops-config in your project, then. Did you already try deleting your node_modules folder and your yarn.lock or package-lock.json files?

**Comment by MikeBild** [comment]
Ahh yes, good point. I figure that out.

**Comment by dmbch** [comment]
@MikeBild is there anything we need to about this in Hops? Would you mind closing this issue otherwise?

**Comment by MikeBild** [comment]
@dmbch Clean up all dependencies made me happy. Thx!
