### ISSUE TITLE
Import bulma css

### ISSUE THREAD

**Issue by ShintaroNippon** [xing/hops#342]
## How to import bulma

i installed bulma then i import in app js
but im getting an error...

node_modules/bulma/bulma.sass:1
(function (exports, require, module, __filename, __dirname) { @charset "utf-8"

**Comment by HerrBertling** [comment]
Looking at your error message, you apparently try to import a `.sass` file – I guess this happens when you `import bulma from 'bulma'`? The `main` entry in the `bulma` `package.json` links to that file: https://github.com/jgthms/bulma/blob/master/package.json#L7

Unfortunately, Hops currently only supports pure CSS files and PostCSS with [cssnext](https://github.com/MoOx/postcss-cssnext) at the moment.

I don't think there are any plans to extend this to include SASS files.

You could however import the `bulma.css` file instead which should work without problems.
