### ISSUE TITLE
Webpack config module rules not extendable any more

### ISSUE THREAD

**Issue by heliosam** [xing/hops#508]
## This is my intent (choose one)

- [ ] I want to report a bug
- [x] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem
Hey guys

We are using styled components together with Hops. In order to do so we were also extending webpack configuration to add https://github.com/styled-components/babel-plugin-styled-components babel plugin.

We were doing so by using webpack-merge (as suggested in https://github.com/xing/hops/blob/05b14091e96dcd7be380434b9b4f73b1b5ea7546/packages/build-config/README.md) and it was working like this:
```es6
merge.smartStrategy({
  "module.rules.use": "replace"
})(hopsConfig, { module: { rules: [extendedBabelLoader] } });
```

However, after updating `hops-config` from `10.0.1` to `10.4` everything broke. I don't know if that was the very first version to break but digging the history I found that these two commits made extending babel configuration not possible anymore:

https://github.com/xing/hops/commit/36cc2db55df330e5d99f5e971a0597a6b1a13a09#diff-60181ed3c4bbd0b9886cab8cb739e6f0

https://github.com/xing/hops/commit/93ddbbfa45a3d72d2de8a16961647801ed2cc2a9#diff-e3928e3fa787fa3595ba29233d23f8b5

My concern is wether if this should've been a major upgrade of hops because I think it is a breaking change. 

Of course we could try to change the way we are extending the config, but I think that's not the point.

## Proposed solution
Keep old module rules structure?
Dump a major version?
Update changelog and include this breaking change?

**Comment by ZauberNerd** [comment]
@heliosam yes, this is part of the webpack 4 upgrade as mentioned in this release: https://github.com/xing/hops/releases/tag/v10.2.0

We decided that webpack configuration files should not be considered API surface, because otherwise this would lead to a lot of "breaking changes" whenever we make changes or updates to the configuration.
Also: This was exposing our filesystem structure as API which makes it harder for us to move things around.

Right now webpack-merge doesn't work anymore, so you will have to import the webpack config, mutate it and return it (see here for an example: https://github.com/foosbyte/kicker-trainer/tree/master/packages/hops-typescript).

We are currently working on a completely new architecture for Hops which will make configuring webpack a lot simpler and will free us from having to treat the filesystem paths as API (see here: https://github.com/xing/hops/pull/490 - based on: https://github.com/untool/untool).

You can find an example of how that would look like for webpack configuration here: https://github.com/foosbyte/kicker-trainer/blob/hops-11/packages/hops-typescript/mixin.core.js
There is also a styled-components mixin which I wrote for a side-project which I will soon integrate into Hops itself: https://github.com/foosbyte/kicker-trainer/tree/hops-11/packages/hops-styled-components

**Comment by heliosam** [comment]
Hey @ZauberNerd thanks for the quick response and thanks for the example, it looks really handy. It is good to hear you are working towards making this easier to configure. 

Now I understand your point, although it was a surprise to find out those changes.

I will check all the links and hopefully make it work until the new version is ready.

Thanks!
