### ISSUE TITLE
Safari & iOS minifying issue

### ISSUE THREAD

**Issue by muehre** [xing/hops#715]
## This is my intent (choose one)

- [x] I want to report a bug
- [ ] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

**Hops Version 10.0.2**
**Safari Version 10.1.2**

Javascript error is blocking react.

> SyntaxError: Cannot declare a const variable twice: 't'.

Maybe related to https://github.com/babel/minify/issues/681?

Is it related to a preset or Browser compatibility?

**Hops Config**
```json
"hops": {
    "presets": [],
    "browsers": "> 0.25%, last 1 versions, Firefox ESR, iOS 10",
    "port": 8081,
    "host": "0.0.0.0",
    "locations": [
      "/"
    ],
    "developConfig": "./config/hops/develop.js"
}
```

Maybe check it @ https://take-a-smile.org/

**Comment by robin-drexler** [comment]
Hey @muehre 
One thing we've noticed, that could cause the issue is that your bundle contains es6 features. In particular we found `const` declarations in your [vendor file](https://take-a-smile.org/vendor-9d3a98b0605ed71d.js) 

This is probably caused by some `nodule_module` exporting es6 code in its main export. In hops 10, we only transpile dependencies that have an explicit `jsnext:main` or `esnext:main` entry in their package.json. Could you try to find said dependency?

If you could provide a minimal reproduction repository, that would also be appreciated. :)

**Comment by robin-drexler** [comment]
If I had to guess, the package in question is probably query-string. Their [advice is to simply install an older version to ensure only es5 is being used](https://github.com/sindresorhus/query-string#install).

**Comment by muehre** [comment]
Downgrading query-string did the trick. Ty @robin-drexler !
