### ISSUE TITLE
make inclusion of cookies in fetch configurable

### ISSUE THREAD

**Issue by SGraef** [xing/hops#844]
## This is my intent (choose one)

- [ ] I want to report a bug
- [X] I want to request a feature or change
- [ ] I want to provide or change a feature

## The problem

The cookie I'm using to identify the user on the backend-server isn't send while server-side-rendering. Since sending cookies for authentication isn't an uncommon way for user detection an option for setting up the cookie sending would really improve the usability from hops. For server communication I used hops-graphql and was able to setup client-side request to use the cookies. 

## Proposed solution

Some configuration option for hops-graphql or even hops directly to configure cookie sending in one central place like the hopsrc or package.json

**Comment by ZauberNerd** [comment]
Hi @SGraef sorry for taking so long to to respond.
Could you please clarify a little bit more, what you need?

As far as I understand, you want to use the cookie that the browser sends to the Hops server when requesting the initial HTML to be forwarded to the GraphQL server from which we fetch the data for server-side rendering?

So that would mean adding the incoming cookie to this `fetch`? https://github.com/xing/hops/blob/master/packages/graphql/mixin.server.js#L65

The main problem I'm seeing here, is that we don't know which cookie should be sent to which domain and in the worst case we could end up leaking sensitive information to third party APIs.

Also it would only work for `hops-graphql`, because for `hops-redux` we don't have control over the fetch implementation the user uses in their thunks.

However when you use our XING internal Hops presets, we do have the option to forward cookies. I'll open a ticket on our internal issue tracker or message you privately about this.

**Comment by ZauberNerd** [comment]
We started to implement this in [`hops-graphql` with #860](https://github.com/xing/hops/pull/860) but realized that it might be more complex than initially thought.

Therefore I would propose you create a custom runtime mixin for now:

1. create a `forward-cookies` folder inside your application root folder
2. create a `mixin.runtime.js` file inside that `forward-cookies` folder
3. register this mixin in your hops config via `mixins: ['./forward-cookies']`

This should be the content of the `mixin.runtime.js` file:
```javascript
const { HttpLink } = require('apollo-link-http');
const { Mixin } = require('hops');
// this allows you to use `fetch` inside Node.js and the browser
// and make it available globally
require('cross-fetch/polyfill');

class ForwardCookiesGraphqlMixin extends Mixin {
  // this hook will only be executed on the server side
  // therefore `this.req` is undefined in the browser
  bootstrap(req) {
    this.req = req;
  }

  getApolloLink() {
    const options = this.req
      ? // when this mixin is run on the server-side `this.req` will be truthy
        // therefore it will pass `headers: { cookie: '...' }` to the
        // apollo-link-http options (https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http#options)
        {
          headers: {
            cookie: this.req.headers.cookie,
          },
        }
      : // in case this mixin is run on the client-side it should configure
        // the apollo-link-http to always include credentials for all requests
        // https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http#options
        { credentials: 'include' };

    console.log(options);

    return new HttpLink({
      uri: this.config.graphqlUri,
      fetch: global.fetch,
      ...options,
    });
  }
}

module.exports = ForwardCookiesGraphqlMixin;
```

**Comment by herschel666** [comment]
There's one thing missing in this recipe iirc. Besides the `mixin.runtime.js` you have to create a file named `preset.js` and put the following contents into it:

```js
module.exports = {
  mixins: [__dirname],
};
```

Only then does Hops become aware of the existence of this custom mixin.

**Comment by ZauberNerd** [comment]
@herschel666 that's not needed, because we register it via `mixins`, not via `presets`

> 3. register this mixin in your hops config via `mixins: ['./forward-cookies']`

**Comment by ZauberNerd** [comment]
I will close this ticket for now and put it in our backlog. At the moment we do not have resources to incorporate this into Hops, but with the above solution it should work for your use-case.
Feel free to re-open / reply if there are any issues remaining.
